# Generated by Django 5.0.6 on 2024-06-24 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="related_nice_habit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="habits.habit",
                verbose_name="связанная привычка",
            ),
        ),
        migrations.RemoveField(
            model_name="habit",
            name="description",
        ),
        migrations.AddField(
            model_name="habit",
            name="action",
            field=models.TextField(default=None, verbose_name="Действие"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="habit",
            name="is_nice",
            field=models.BooleanField(
                default=False, verbose_name="признак приятной привычки"
            ),
        ),
        migrations.DeleteModel(
            name="NiceHabit",
        ),
    ]
