# Generated by Django 5.0.6 on 2024-06-27 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0003_alter_habit_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="send_date",
            field=models.DateField(
                auto_now=True, null=True, verbose_name="дата начала отправки"
            ),
        ),
    ]
