# Generated by Django 5.0.6 on 2024-06-27 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0004_habit_send_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="send_date",
            field=models.DateField(
                auto_now_add=True, null=True, verbose_name="дата начала отправки"
            ),
        ),
    ]
