# Generated by Django 5.0.6 on 2024-06-29 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0005_alter_habit_send_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="action",
            field=models.TextField(
                help_text="Опишите действие по примеру: 'ходить в спортзал'",
                verbose_name="Действие",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="name",
            field=models.CharField(
                help_text="Назовите свою привычку(например, 'Спортзал')",
                verbose_name="Название привычки",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="periodicity",
            field=models.IntegerField(
                default=1,
                help_text="Укажите периодичность от 1 до 7, где 1 - один раз в неделю, а 7 - это каждый день",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="place",
            field=models.TextField(
                blank=True,
                help_text="Укажите место по примеру: 'спортзал'",
                null=True,
                verbose_name="место",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="time",
            field=models.TimeField(
                default="18:00:00",
                help_text="Укажите время по примеру: '18:00:00'",
                verbose_name="время",
            ),
        ),
    ]
